name: build current

# Controls when the workflow will run
on:
  # Build on saturday
  schedule:
    - cron: "47 3 * * 6"

  # Triggers the workflow on push or pull request
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-bmda:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "blackmagic-debug/blackmagic"

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git zip mingw-w64-ucrt-x86_64-toolchain
          pacboy: libusb:p libftdi:p hidapi:p

      - name: build
        run: |
          rm -fv /ucrt64/lib/libftdi1.dll.a /ucrt64/lib/libhidapi.dll.a /ucrt64/lib/libusb-1.0.dll.a
          mingw32-make PROBE_HOST=hosted HOSTED_BMP_ONLY=0
          zip -j9 bmda.zip src/blackmagic.exe

      - uses: actions/upload-artifact@v3
        with:
          name: bmda
          path: bmda.zip
          retention-days: 1

  build-firmware:
    runs-on: ubuntu-latest
    needs: build-bmda

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: "blackmagic-debug/blackmagic"

      - name: Get commit hash
        id: getcommit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Report commit hash
        run: echo ${{ steps.getcommit.outputs.sha_short }}

      - uses: actions/checkout@v3
        with:
          path: "bmp"

      - name: Patch
        run: patch -p1 -i bmp/blackmagic.patch

      # Setup and use a suitable ARM GCC for the firmware
      - name: Setup ARM GCC
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.2.Rel1'

      - name: Install BMDA dependencies
        run: sudo apt-get -y install libusb-dev libftdi1-dev libhidapi-dev

      - name: Build all platform firmwares and Linux BMDA
        run: make all_platforms

      - uses: actions/download-artifact@v3
        with:
          name: bmda

      - name: Unzip windows bmda
        run: unzip bmda.zip -d src/artifacts/hosted

      - name: Zip
        run: ( ln -s src/artifacts blackmagic-firmware-${{ steps.getcommit.outputs.sha_short }}; zip -r9 blackmagic-firmware.zip blackmagic-firmware-${{ steps.getcommit.outputs.sha_short }}/ )

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "blackmagic-firmware.zip"
          body: "bmp firmware, current git"
          tag: current
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

# not truncated
